[package]
name = "nccl"
version = "1.0.0"
authors = ["Zack <zphixon@gmail.com>"]
description = "Minimal configuration file format and library."
documentation = "https://docs.rs/nccl"
homepage = "https://github.com/zphixon/nccl"
repository = "https://github.com/zphixon/nccl"
keywords = ["nccl", "configuration", "config"]
categories = ["config"]
license = "MIT"
readme = "README.md"
edition = "2018"

[badges]
travis-ci = { repository = "zphixon/nccl" }

[dependencies]
